set shell := ["cmd.exe", "/c"]

asm:
    nasm -f win64 asm/script.asm -o script.o
    gcc script.o -o script
    script.exe
    del script.exe
    del script.o

watch:
    nodemon -e asm -x "just asm"